insert into professions (name, description, hp_modifier, primary_ability, trait_one, trait_two, trait_three, trait_four)
values  ('Barbarian', 'A Barbarian is a brutish melee attacker who uses their rage to empower their attacks with reckless abandon.', 12, 'Strength', 'Rage', 'Unarmored Defense (Constitution)', 'Reckless Attack', 'Great Weapon Master'),
        ('Bard', 'A Bard is a charismatic musician who uses the power of magic to support and inspire their allies and confuse and control enemies.', 8, 'Charisma', 'Vicious Mockery', 'Bardic Inspiration', 'Mantle of Majesty', 'Song of Rest'),
        ('Cleric', 'A Cleric is a devout individual who receives spellcasting powers via worship of a deity, which they use for devastating attacks and protective magics.', 8, 'Wisdom', 'Channel Divinity', 'Turn Undead', 'Blessed Strikes', 'Divine Intervention'),
        ('Druid', 'A Druid is a peaceful individual who lives in harmony with nature, being able to shape into animals to support their allies.', 8, 'Wisdom', 'Wild Shaping', 'Regrowth', 'Speak with Animals and Plants', 'Ageless'),
        ('Fighter', 'A Fighter is a trained attacker who has honed their skill in combat to deliver devastating attacks.', 10, 'Strength', 'Parry', 'Shield Master', 'Second Wind', 'Extra Attack'),
        ('Monk', 'A Monk is a disciplined martial artist who channels the power of their spirit into their fists to make lightning-fast strikes.', 8, 'Dexterity', 'Ki Points', 'Unarmored Defense (Wisdom)', 'Flurry of Blows', 'Deflect Attack'),
        ('Paladin', 'A paladin is a lawful and devout knight who emboldens their resolve by binding themselves to an oath', 10, 'Strength', 'Smite', 'Divine Shield', 'Mounted Combat', 'Penance'),
        ('Ranger', 'A Ranger is accustomed to live in the wilds, using their knowledge of nature to support allies and control the battlefield.', 10, 'Dexterity', 'Animal Companion', 'Trapping', 'Foraging', 'Snipe Shot'),
        ('Rogue', 'A Rogue is a thief who hides in the shadows and ambushes enemies to deal crippling sneak attacks.', 8, 'Dexterity', 'Stealth', 'Sneak Attack', 'Parlor Tricks', 'Tricks of the Trade'),
        ('Sorcerer', 'A Sorcerer is a spellcaster who has gained magic ability through birth or an uncommon occurrence', 6, 'Charisma', 'Metamagic', 'Telepath', 'Magic Veins', 'Mystic Arcanum'),
        ('Warlock', 'A Warlock received spellcasting powers through a pact they have made with a powerful patron.', 8, 'Charisma', 'Pact Magic', 'Eldritch Invocations', 'Mind Games', 'Ritualist'),
        ('Wizard', 'A Wizard has studied magic meticulously, gaining spellcasting powers through sheer knowledge.', 6, 'Intelligence', 'Spell Book', 'Transcribe Scroll', 'Familiar', 'Recuperate');

insert into specializations (name, description, traitOne, traitTwo, traitThree, traitFour)
values  ('Path of the Totem', 'The Barbarian channels the bestial powers of a totem spirit, giving them bestial powers.', '', '', '', ''),
        ('Path of the World Tree', 'The Barbarian channels the power of the world tree, giving them spectral battlefield manipulation.', '', '', '', ''),
        ('Path of the Berserker', 'The Barbarian channels their rage, mitigating incoming damage.', '', '', '', ''),
        ('College of Valour', 'The Bard studied at the College of Valour, boosting melee capabilities.', '', '', '', ''),
        ('College of Eloquence', 'The Bard studied at the College of Eloquence, enhancing the power of their words.', '', '', '', ''),
        ('College of Spirits', 'The Bard studied at the College of Spirits, granting them spiritual, mind-altering capabilities.', '', '', '', ''),
        ('Twilight Domain', 'The Cleric worships a deity of balance, resulting in strong support capabilities.', '', '', '', ''),
        ('War Domain', 'The Cleric uses their divine powers for powerful battlefield capabilities.', '', '', '', ''),
        ('Light Domain', 'The Cleric uses their divine power for empowered healing and boons.', '', '', '', ''),
        ('Circle of Spores', 'The Circle of Spores honors the role of decay in the natural cycle of life, granting them persistent damaging buffs.', '', '', '', ''),
        ('Circle of the Moon', 'The Circle of the Moon honors the changing shape of the moon, empowering their Wild Shaping capabilities.', '', '', '', ''),
        ('Circle of Stars', 'The Circle of Stars honors the constellations in the night sky, granting them the power to Wild Shape into Starry Forms', '', '', '', ''),
        ('Battle Master', 'The Battle Master can employ a plethora of battle manoeuvres, allowing them stronger manipulation of their enemies.', '', '', '', ''),
        ('Champion', 'The Champion ues a heightened insight in the anatomy of their targets to deliver devastating critical strikes.', '', '', '', ''),
        ('Eldritch Knight', 'The Eldritch Knight uses supportive magic, supplementing their weapon attacks with deadly magical effects.', '', '', '', ''),
        ('Way of the Open Hand', 'Following the Way of the Open Hand boosts unarmed capabilities.', '', '', '', ''),
        ('Way of Shadows', 'Following the Way of Shadows enables short-range teleportation into shadows and vision manipulation through magical darkness.', '', '', '', ''),
        ('Way of Mercy', 'Following the Way of Mercy grants the monk powerful execution strikes.', '', '', '', ''),
        ('Oath of Conquest', 'Making an Oath of Conquest empowers the spell damage output of the Paladin.', '', '', '', ''),
        ('Oath of Devotion', 'Making an Oath of Devotion doubles down on the damage output against fiends, undead and abberations.', '', '', '', ''),
        ('Oathbreaker', 'Breaking an Oath results in a twisted morality, a command of the undead and a frightening presence to control enemies.', '', '', '', ''),
        ('Drakewarden', 'A Drakewarden prefers taming dragonkin as their companion, granting the Ranger elemental powers.', '', '', '', ''),
        ('Gloom Stalker', 'A Gloom Stalker keeps to the shadows to deliver deadly precision strikes.', '', '', '', ''),
        ('Swarmkeeper', 'A Swarmkeeper specializes in large hordes of tiny creatures to pester their enemies into submission and defeat.', '', '', '', ''),
        ('Assassin', 'An Assassin delivers deadly precision strikes, often without ever being seen.', '', '', '', ''),
        ('Phantom', 'A Phantom is able to control visibility in battle, and employs mind-bending tactics to confuse enemies.', '', '', '', ''),
        ('Swashbuckler', 'A Swashbuckler has mastered underhanded tactics to incapacitate enemies and manipulate the rules of engagement.', '', '', '', ''),
        ('Draconic Bloodline', 'A draconic ancestor is the source of strong elemental magics in this sorcerer.', '', '', '', ''),
        ('Aberrant Mind', 'From a young age, this Sorcerer has exhibited psionic powers, now translating into powerful manipulative spells.', '', '', '', ''),
        ('Clockwork Soul', 'An encounter with the Plane of Order has left this Sorcerer with powerful reality-warping abilities.', '', '', '', ''),
        ('The Undying', 'A pact with an Undying creature empowers the warlock with a command over the undead and a mastery over death (and avoiding it).', '', '', '', ''),
        ('The Fiend', 'A pact with a demon in the Nine Hells has given the warlock strong elemental magic and power over planar banishment.', '', '', '', ''),
        ('The Great Old One', 'A pact with an eldritch outer god has given the warlock the ability to control the minds of others to instill fear or manipulate social interactions.', '', '', '', ''),
        ('School of Divination', 'The Wizard has studied Divination spells in particular, empowering the gift of Foresight to gain an advantage in future encounters', '', '', '', ''),
        ('School of Evocation', 'The Wizard has studied Evocation spells in particular, boosting their raw magical damage output and enabling them to avoid damaging their allies.', '', '', '', ''),
        ('School of Abjuration', 'The Wizard has studied Abjuration spells in particular, boosting their defensive spells and granting them the power to conjure powerful shields.', '', '', '', '');